## Python3 错误和异常

---
### 语法错误

Python 的语法错误或者称之为解析错，

---
### 异常

#### try/except

except 英 /ɪkˈsept/  美 /ɪkˈsept/ prep. 除……之外 conj. 只是；除非；除……之外；要不是由于 v. 不计，把……除外；反对

异常捕捉可以使用 try/except 语句。
```
while True:
    try:
        x = int(input('请输入一个数字：'))
        break
    except ValueError:
        print("您输入的不是数字，请再次尝试输入！")
```

一个 try 语句可能包含多个except子句，分别来处理不同的特定的异常。最多只有一个分支会被执行。

处理程序将只针对对应的 try 子句中的异常进行处理，而不是其他的 try 的处理程序中的异常。

一个except子句可以同时处理多个异常，这些异常将被放在一个括号里成为一个元组，例如:
```
except (RuntimeError, TypeError, NameError):
    pass
```

最后一个except子句可以忽略异常的名称，它将被当作通配符使用。你可以使用这种方法打印一个错误信息，然后再次把异常抛出。
```
import sys

try:
    f = open('test.txt', 'r')
    s = f.readline() #读取第一行
    i = int(s.strip())
except OSError as err:
    print('OS error：{0}'.format(err))
except ValueError:
    print('"Could not convert data to an integer.')
except:
    print('Unexpected error: {0}'.format(sys.exc_info()))
    raise
```

raise 英 /reɪz/  美 /reɪz/  vt. 提高；筹集；养育；升起；饲养，种植 vi. 上升 n. 高地；上升；加薪

#### try/except...else

try/except 语句还有一个可选的 else 子句，如果使用这个子句，那么必须放在所有的 except 子句之后。
else 子句将在 try 子句没有发生任何异常的时候执行。
```
import sys
print(sys.argv) #['F:/Study_objectMenu/Python/Object_hello/hello.py']
for arg in sys.argv[1:]:
    try:
        f = open(arg, 'r')
    except IOError:
        print('cannot open', arg)
    else:
        print(arg, 'has', len(f.readlines()), 'lines')
        f.close()
```

#### try-finally 语句

try-finally 语句无论是否发生异常都将执行最后的代码。

```
try:
    runoob()
except AssertionError as error:
    print(error)
else:
    try:
        with open('file.log') as file: #as别名
            read_data = file.read()
    except FileNotFoundError as fnf_error:
        print(fnf_error)
finally:
    print('这句话，无论异常是否发生都会执行。')
```

### 抛出异常raise、raise Exception()、raise 错误类型函数和名称

Python 使用 raise 语句抛出一个指定的异常。

raise 抛出 英 /reɪz/  美 /reɪz/ vt. 提高；筹集；养育；升起；饲养，种植 vi. 上升 n. 高地；上升；加薪
Exception 英 /ɪkˈsepʃn/  美 /ɪkˈsepʃn/ n. 例外；异议 复数 exceptions
traceback n. 回溯

```
raise [Exception [, args [, traceback]]]
```

```
x = 10
if x > 5:
    raise Exception('x 不能大于 5。x 的值为: {}'.format(x))
```
输出：
>
Traceback (most recent call last):
  File "F:/Study_objectMenu/Python/Object_hello/hello.py", line 7, in <module>
    raise Exception('x 不能大于 5。x 的值为: {}'.format(x))
Exception: x 不能大于 5。x 的值为: 10


raise 唯一的一个参数指定了要被抛出的异常。它必须是一个异常的实例或者是异常的类（也就是 Exception 的子类）。
如果你只想知道这是否抛出了一个异常，并不想去处理它，那么一个简单的 raise 语句就可以再次把它抛出。
```
try:
    raise NameError('HiThere')
except NameError:
    print('An exception flew by!')
    raise
```
输出：
> 
Traceback (most recent call last):
  File "F:/Study_objectMenu/Python/Object_hello/hello.py", line 6, in <module>
    raise NameError('HiThere')
NameError: HiThere


---
### 用户自定义异常

你可以通过创建一个新的异常类来拥有自己的异常。异常类继承自 Exception 类，可以直接继承，或者间接继承，例如:
```
class MyError(Exception):
    def __int__(self, value):
        self.value = value
    def __str__(self):
        return repr(self.value) #repr() 函数将对象转化为供解释器读取的形式。

try:
    raise MyError(2 * 2)
except MyError as e: #as别名
    print('My exception occurred, value:', e.value)
```

在这个例子中，类 Exception 默认的 __init__() 被覆盖。

当创建一个模块有可能抛出多种不同的异常时，一种通常的做法是为这个包建立一个基础异常类，然后基于这个基础类为不同的错误情况创建不同的子类:
```

```

Transition 英 /trænˈzɪʃn; trænˈsɪʃn/  美 /trænˈzɪʃn,trænˈsɪʃn/ n. 过渡；转变；[分子生物] 转换；变调 复数 transitions过去式 transitioned现在分词 transitioning第三人称单数 transitions
```
class Error(Exception):
    """
        Base class for exceptions in this module.
        此模块中用于异常的基类。
    """
    pass

class InputError(Error):
    """
        Exception raised for errors in the input.输入错误引发的异常

        Attributes:属性
            expression -- input expression in which the error occurred
            表达式——发生错误的输入表达式
            message -- explanation of the error
            消息——错误的解释
    """
    def __int__(self, expression, message):
        self.expression = expression
        self.message = message

class TransitionError(Error):
    """
        Raised when an operation attempts a state transition that's not allowed.
        当操作尝试不允许的状态转换时引发

        Attributes:属性
            previous -- state at beginning of transition
            previous——过渡开始时的状态
            next -- attempted new state
            接下来——尝试进入新状态
            message -- explanation of why the specific transition is not allowed
            消息——解释为什么不允许特定的转换
    """
    def __int__(self, previous, next, message):
        self.previous = previous
        self.next = next
        self.message = message
```

大多数的异常的名字都以"Error"结尾，就跟标准的异常命名一样。


---
### 定义清理行为

try 语句还有另外一个可选的子句，它定义了无论在任何情况下都会执行的**清理行为**。 例如:
```
try:
    raise KeyboardInterrupt
finally:
    print('Goodbye, world!')
```

```
def divide(x, y):
    try:
        result = x / y
    except ZeroDivisionError:
        print("division by zero!")
    else:
        print("result is", result)
    finally:
        print("executing finally clause")

divide(2, 1) 
```
输出：
> 
result is 2.0
executing finally clause


### 预定义的清理行为 with ... as name

一些对象定义了标准的清理行为，无论系统是否成功的使用了它，一旦不需要它了，那么这个标准的清理行为就会执行。

键词 with 语句就可以保证诸如文件之类的对象在使用完之后一定会正确的执行他的清理方法:
```
with open('test/test.txt') as f:
    for line in f:
        print(line)
```